name: login_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  # 추가한 패키지
  dio: ^5.8.0+1
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.1
  provider: ^6.1.2
  http: ^0.13.6
  # 소셜 로그인
  google_sign_in: ^5.4.1
  naver_login_sdk: ^3.0.0
  kakao_flutter_sdk_user: ^1.9.5

  # Firebase 의존성
  firebase_auth: ^5.5.3
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/