// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1V92YpmtI7kxMv1u0D4w3EQB9InSonh8',
    appId: '1:940619866029:web:c92e5153819f2059ec8b24',
    messagingSenderId: '940619866029',
    projectId: 'login-app-sample-ec88f',
    authDomain: 'login-app-sample-ec88f.firebaseapp.com',
    storageBucket: 'login-app-sample-ec88f.firebasestorage.app',
    measurementId: 'G-SFPYJ7LJRV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbVz4BlIOnf37zonK0heRRjR-V9yWt48c',
    appId: '1:940619866029:android:a989a688596ef48dec8b24',
    messagingSenderId: '940619866029',
    projectId: 'login-app-sample-ec88f',
    storageBucket: 'login-app-sample-ec88f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCb2k2GH1x6aXerVIDwo5asCnR8URCsT1w',
    appId: '1:940619866029:ios:1b7992a9ed3b9bb0ec8b24',
    messagingSenderId: '940619866029',
    projectId: 'login-app-sample-ec88f',
    storageBucket: 'login-app-sample-ec88f.firebasestorage.app',
    androidClientId: '940619866029-qc0ltrh51ji3mf7eh7odhkau1fl7k5j7.apps.googleusercontent.com',
    iosClientId: '940619866029-ce4feljvn45bgtn6nh99gdl4ktk46shc.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCb2k2GH1x6aXerVIDwo5asCnR8URCsT1w',
    appId: '1:940619866029:ios:1b7992a9ed3b9bb0ec8b24',
    messagingSenderId: '940619866029',
    projectId: 'login-app-sample-ec88f',
    storageBucket: 'login-app-sample-ec88f.firebasestorage.app',
    androidClientId: '940619866029-qc0ltrh51ji3mf7eh7odhkau1fl7k5j7.apps.googleusercontent.com',
    iosClientId: '940619866029-ce4feljvn45bgtn6nh99gdl4ktk46shc.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1V92YpmtI7kxMv1u0D4w3EQB9InSonh8',
    appId: '1:940619866029:web:89249387a4999adcec8b24',
    messagingSenderId: '940619866029',
    projectId: 'login-app-sample-ec88f',
    authDomain: 'login-app-sample-ec88f.firebaseapp.com',
    storageBucket: 'login-app-sample-ec88f.firebasestorage.app',
    measurementId: 'G-EE4YJ6J35J',
  );
}
